#!/bin/bash

GEM=`which gem2.0`

if [ "$GEM" = "" ]
then
  GEM=gem
fi

echo "ALMiniumをアンインストールします。"
echo ""
echo -n "データベース(全てのRedmineの情報)とリポジトリを削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    mysql alminium -e "REVOKE ALL ON alminium.* FROM alminium@localhost"
    mysql alminium -e "DELETE FROM mysql.user WHERE User LIKE 'alminium'"
    mysql alminium -e "FLUSH PRIVILEGES"
    mysql alminium -e "DROP DATABASE alminium"
    rm -fr /opt/alminium /var/opt/alminium
fi


echo ""
echo -n "Apacheの設定を削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    rm -fr /etc/httpd/conf.d/{alminium,passenger}.conf
    rm -fr /etc/apache2/conf.d/{alminium,passenger}.conf
    rm -fr /etc/apache2/sites-{available,enabled}/alminium.conf
    rm -fr /etc/apache2/mods-{available,enabled}/passenger.load
    rm -fr /opt/local/apache2/conf/{alminium,passenger}.conf
    rm -fr /etc/opt/alminium
fi


echo ""
echo -n "Jenkisとその設定を削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    source jenkins/setup/uninstall.sh
fi


echo ""
echo -n "キャッシュされたファイルを削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    rm -fr cache *.installed
fi
