#!/bin/bash

GEM=`which gem2.0`

if [ "$GEM" = "" ]
then
  GEM=gem
fi

echo "ALMiniumをアンインストールします。"
echo ""
echo -n "データベース(全てのRedmineの情報)とリポジトリを削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    mysql alminium -e "REVOKE ALL ON alminium.* FROM alminium@localhost"
    mysql alminium -e "DELETE FROM mysql.user WHERE User LIKE 'alminium'"
    mysql alminium -e "FLUSH PRIVILEGES"
    mysql alminium -e "DROP DATABASE alminium"
    rm -fr /opt/alminium /var/opt/alminium
fi

echo ""
echo -n "Apacheの設定を削除しますか?(y/N)"
read YN


if [ "$YN" = "y" ]
then
    rm -fr /etc/apache2/sites-{available,enabled}/jenkins
    rm -fr /etc/apache2/sites-{available,enabled}/redmine
    rm -fr /etc/apache2/sites-{available,enabled}/vcs
    rm -fr /etc/httpd/conf.d/jenkins.conf
    rm -fr /etc/httpd/conf.d/redmine.conf
    rm -fr /etc/httpd/conf.d/vcs.conf
    rm -fr /etc/opt/alminium
fi

echo ""
echo -n "Passengerを削除しますか?(y/N)"
read YN


if [ "$YN" = "y" ]
then
    echo "3" | $GEM uninstall passenger
fi

echo ""
echo -n "Jenkisとその設定を削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]
then
    if [ -f /usr/bin/yum ]; then
        yum -y remove jenkins
    elif [ -f /usr/bin/apt-get ]; then
        apt-get -y purge jenkins
    fi
    rm -fr /var/lib/jenkins
fi

echo ""
echo -n "キャッシュされたファイルを削除しますか?(y/N)"
read YN


if [ "$YN" = "y" ]
then
    rm -fr cache *.installed
fi
