#!/bin/bash
# rubygems.lstからgemのリストを取得しインストール

GEM=`which gem2.0`

if [ "$GEM" = "" ]
then
  GEM=gem
fi

# インストールするディレクトリ名
NAME=(`grep -v "^#" inst-script/rubygems.lst | awk -F, '{print $1}'`)
VER=(`grep -v "^#" inst-script/rubygems.lst | awk -F, '{print $2}'`)

for (( i = 0; i < ${#NAME[@]}; ++i ))
do
  NAME=${NAME[$i]}
  VER=${VER[$i]}
  if [ "$VER" = "-" ]
  then
    $GEM install -f $NAME --no-rdoc --no-ri
  else
    $GEM install -f $NAME -v=$VER --no-rdoc --no-ri
  fi
done
