#!/bin/bash

if [ ! -f /etc/perl/Apache/Authn/Redmine.pm ]
then
  mkdir -p /etc/perl/Apache/Authn
  cat  etc/Redmine.pm |sed 's/Digest::SHA1/Digest::SHA/g' > /etc/perl/Apache/Authn/Redmine.pm
fi

for FILE in $(ls etc/ | grep '.conf$')
do
  sed -e 's/#HOSTNAME#/'$HOSTNAME'/' \
      -e 's/#'$OS'# *//' \
      "etc/$FILE" > "$ALM_ETC_DIR/$FILE"
done

for FILE in $(ls "$ALM_ETC_DIR/" | grep '.conf$')
do
  ln -sf "$ALM_ETC_DIR/$FILE" "$APACHE_CONF_DIR/$FILE"
done

a2enmod expires
a2enmod dav_fs
a2enmod auth_mysql
a2enmod authz_svn
a2enmod proxy_http
a2enmod headers
a2enmod rewrite

service apache2 stop
service apache2 start
