#!/bin/bash

if [ ! -f /etc/perl/Apache/Authn/Redmine.pm ]
then
  mkdir -p /etc/perl/Apache/Authn
  cat  etc/Redmine.pm |sed 's/Digest::SHA1/Digest::SHA/g' > /etc/perl/Apache/Authn/Redmine.pm
fi

if [ "SSL" = "Y" ]; then REPLACE_SSL="#SSL# *"; fi
if [ "ENABLE_JENKINS" = "Y" ]; then REPLACE_JENKINS="#JENKINS# *"; fi
for FILE in $(ls etc/ | grep '.conf$')
do
  sed -e 's/#HOSTNAME#/'$HOSTNAME'/' \
      -e 's/#'$OS'# *//' \
      -e 's/'$REPLACE_SSL'//' \
      -e 's/'$REPLACE_JENKINS'//' \
      "etc/$FILE" > "$ALM_ETC_DIR/$FILE"
done

if [ $(apachectl -v | grep -o 'Apache\/2\.[24]') = "Apache/2.2" ]
then
  ln -sf "$ALM_ETC_DIR/passenger.conf" "$APACHE_CONF_DIR/"
  ln -sf "$ALM_ETC_DIR/alminium.conf"  "$APACHE_CONF_DIR/"
else
  ln -sf "$ALM_ETC_DIR/passenger.conf" "/etc/apache2/mods-available/passenger.load"
  ln -sf "$ALM_ETC_DIR/alminium.conf"  "/etc/apache2/sites-available/"
  a2enmod passenger
  a2ensite alminium.conf
fi

a2enmod expires
a2enmod dav_fs
a2enmod auth_mysql
a2enmod authz_svn
a2enmod proxy_http
a2enmod headers
a2enmod rewrite

service apache2 stop
service apache2 start

# vim: set ts=2 sw=2 et:
