#!/bin/bash
apt-get -q2 update
apt-get -y install `grep -v "^#" inst-script/debian/packages.lst`
REALLY_GEM_UPDATE_SYSTEM=1 gem update --system

if [ "$SSL" = "y" ]
then
    apt-get -y install libapache2-mod-gnutls ssl-cert
    a2enmod ssl rewrite
fi

service mysql start
